apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  selector:
    matchLabels:
      app: neo4j
  template:
    volumes: 
      - name: neo4j-storage
        persistentVolumeClaim:
          claimName: neo4j-pv-claim
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:community
        ports:
        - containerPort: 7474
        - containerPort: 7687
        env:
          - name: "NEO4J_AUTH"
            value: "neo4j/mysecretpassword"
          - name: "NEO4J_server_config_strict__validation_enabled"
            value: "false"
          - name: "NEO4J_apoc_export_file_enabled"
            value: "true"
          - name: "NEO4J_apoc_import_file_enabled"
            value: "true"
          - name: "NEO4J_apoc_import_file_use__neo4j__config"
            value: "true"
          - name: "NEO4J_PLUGINS"
            value: "[\"apoc\"]"
        volumeMounts:
          - mountPath: "/data"
            name: neo4j-storage